GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes/ HTTP/1.1
Content-Type: application/json

{
   "content": "I figured it out! Hehey!",
   "important": true,
   "userId": "6673b7bf6bbf83a0dfb81a1d"
}

###
DELETE http://localhost:3001/api/notes/4

###
PUT http://localhost:3001/api/notes/6654974c890221d9a364717d HTTP/1.1
Content-Type: application/json

{
    "content": "Ensuring that everything's working",
    "important": false
}

###
POST http://localhost:3001/api/users/ HTTP/1.1
Content-Type: application/json

{
   "username": "vovka",
   "name": "Vova",
   "password": "abcdef",
   "notes": []
}